name: AdminMode
main: io.github.Thomdare.Main
version: 0.1
author: Thomdare
commands:
  adminmode:
    description: Toggles Admin Mode.
    usage: "/adminmode"
  modmode:
    description: Toggles Mode Mode.
    usage: "/modmode"
